### PR TITLE
alert-duties-24.10.01 npm audit fix

### PR DESCRIPTION
**Pull request by marcusaleman**
As MAP developer on alert duties,

I have addressed npm audit dependencies updated

### CODE REVIEW

**Review by tobyprivett — APPROVED** [review]

**Comment by jnioche-jd** [comment]
@marcusaleman can you add in the description a link to alert which is PR should fix (or copy its content)?
as discussed in the call, some of the dependency updates are probably already covered by PRs generated by Dependabot or Renovate. Would be best to try those first as they are specific to a given library

**Comment by jnioche-jd** [comment]
https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-registers/2715/workflows/5e996896-cf5d-4db9-b441-3e37eef154f2

**Comment by jnioche-jd** [comment]
Shouldn't package.json be modified as well? See https://github.com/ministryofjustice/hmpps-registers/pull/282/files

**Review by jnioche-jd — CHANGES_REQUESTED** [review]
Let's not merge this as is but: 

- address the specific libraries which triggered the alerts
- look at existing PRs from dependabot
- compare with versions in the templates (where relevant)

**Comment by jnioche-jd** [comment]
@marcusaleman please don't leave issues open unnecessarily

**Pull request closed without merging**
